version: "3.7"
services:
  nginxtended:
    image: wowmuchname/nginxtended:1.17.0
    volumes:
      - certs:/etc/letsencrypt
      - backends:/backends
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-net
    container_name: nginxtended
volumes:
  certs:
    external: true
  backends:
    external: true
networks:
  proxy-net:
    external: true
