version: "3.3"
services:
  proxyx:
    image: proxyx
    volumes:
      - "backends:/backends"
      - "certs:/certs"
      - /var/run/docker.sock:/var/run/docker.sock
#      - stream-test:/etc/nginx/stream-conf.d
    networks:
      - proxy-net
    ports:
      - 27000:27000
      - 80:80
      - 443:443
networks:
  proxy-net:
    external: true
volumes:
  certs:
    external: true
  backends:
    external: true
#  stream-test:
#    external: true
